AppDebug: true   # 璁剧疆绋嬪簭鎵€澶勭殑妯″紡锛宒ebug=true 璋冭瘯妯″紡锛屾棩蹇椾紭鍏堟樉绀哄湪鎺у埗鍙帮紝 debug=false 闈炶皟璇曟ā寮忥紝鏃ュ織灏嗗啓鍏ユ棩蹇楁枃浠?

HttpServer:
  Web:
    Port: ":22001"                  #鍚庣搴旂敤绫荤鍙?娉ㄦ剰鍓嶉潰鏈夊啋鍙?
  AllowCrossDomain: true    #鏄惁鍏佽璺ㄥ煙锛岄粯璁?鍏佽锛屾洿澶氬叧浜庤法鍩熺殑浠嬬粛浠庡弬鑰冿細https://www.yuque.com/xiaofensinixidaouxiang/bkfhct/kxddzd
  TrustProxies:                     #璁剧疆gin鍙互淇′换鐨勪唬鐞嗘湇鍔″櫒(渚嬪 nginx 鍓嶇疆浠ｇ悊鏈嶅姟鍣?,璇︽儏鍙傝鏂囨。锛歨ttps://www.yuque.com/xiaofensinixidaouxiang/bkfhct/vmobe7
    IsOpen: 0                        # 鍙€夊€硷紙0 鎴栬€?1锛?濡傛灉 go 鏈嶅姟鏄 nginx 浠ｇ悊锛屽缓璁鍊艰缃负 1锛屽皢 nginx 浠ｇ悊鍙婃満鍣ㄧ殑ip娣诲姞鍒?ProxyServerList 鍒楄〃
    ProxyServerList:
      - "192.168.10.1"             # nginx 浠ｇ悊鏈嶅姟鍣╥p鍦板潃
      - "192.168.10.2"
Token:
  JwtTokenSignKey:  "douyin-backend"   #璁剧疆token鐢熸垚鏃跺姞瀵嗙殑绛惧悕
  JwtDefaultUid: 1 # 榛樿鐢ㄦ埛 id
  JwtTokenOnlineUsers:  3         #涓€涓处鍙峰瘑鐮佸厑璁告渶澶ц幏鍙栧嚑涓湁鏁堢殑token锛屽綋瓒呰繃杩欎釜鍊硷紝绗竴娆¤幏鍙栫殑token鐨勮处鍙枫€佸瘑鐮佸氨浼氬け鏁?
  JwtTokenCreatedExpireAt: 28800   #鍒涘缓鏃秚oken榛樿鏈夋晥绉掓暟锛坱oken鐢熸垚鏃堕棿鍔犱笂璇ユ椂闂寸鏁帮紝绠楀仛鏈夋晥鏈燂級,3600*8=28800 绛変簬8灏忔椂
  JwtTokenRefreshAllowSec: 86400   #瀵逛簬杩囨湡鐨則oken锛屽厑璁稿湪澶氬皯灏忔椂涔嬪唴鍒锋柊锛岃秴杩囨鏃堕棿鍒欎笉鍏佽鍒锋柊鎹㈠彇鏂皌oken锛?6400=3600*24锛屽嵆token杩囨湡24灏忔椂涔嬪唴鍏佽鎹㈡柊token
  JwtTokenRefreshExpireAt: 36000   #瀵逛簬杩囨湡鐨則oken锛屾敮鎸佷粠鐩稿叧鎺ュ彛鍒锋柊鑾峰彇鏂扮殑token锛屽畠鏈夋晥鏈熶负10涓皬鏃讹紝3600*10=36000 绛変簬10灏忔椂
  BindContextKeyName: "userToken"  #鐢ㄦ埛鍦?header 澶撮儴鎻愪氦鐨則oken缁戝畾鍒颁笂涓嬫枃鏃剁殑閿悕锛屾柟渚跨洿鎺ヤ粠涓婁笅鏂?gin.context)鐩存帴鑾峰彇姣忎釜鐢ㄦ埛鐨刬d绛変俊鎭?
  IsCacheToRedis: 1                #鐢ㄦ埛token鏄惁缂撳瓨鍒皉edis, 濡傛灉宸茬粡姝ｇ‘閰嶇疆浜唕edis,寤鸿璁剧疆涓?, 寮€鍚痳edis缂撳瓨token锛岋紙1=鐢ㄦ埛token缂撳瓨鍒皉edis; 0=token鍙瓨鍦ㄤ簬mysql锛?

LoginPolicy:                       #璐﹀彿鐧婚檰绛栫暐锛屽缓璁紑鍙戣€呴厤缃畆edis锛屽紑鍚鍔熻兘
  IsOpenPolicy: 0                  #璇ュ姛鑳戒緷璧栦簬redis锛屽綋寮€鍚鍔熻兘蹇呴』淇濊瘉redis閰嶇疆姝ｇ‘锛?=涓嶉檺鍒讹紱1=鍚敤鐧婚檰瀹夊叏绛栫暐
  MaxLoginFailTimes: 3             #鐧婚檰杩炵画澶辫触鐨勬渶澶ф鏁?
  LoginFailCountDown: 120          #杩炵画鐧婚檰澶辫触瓒呴檺鍚庨檺鍒?20绉?璇疯嚜琛屼慨鏀?鍐呯姝㈢櫥闄?

Redis:
  Host: "127.0.0.1"
  Port: 6379
  Auth: ""  # 璁剧疆浣犵殑redis瀵嗙爜
  MaxIdle: 10
  MaxActive: 1000
  IdleTimeout: 60
  IndexDb: 1               # 榛樿杩炴帴鐨剅edis鏄?鍙锋暟鎹簱锛屼笉鏄?鍙锋暟鎹簱
  ConnFailRetryTimes: 3    #浠庤繛鎺ユ睜鑾峰彇杩炴帴澶辫触锛屾渶澶ч噸璇曟鏁?
  ReConnectInterval: 1     # 浠庤繛鎺ユ睜鑾峰彇杩炴帴澶辫触锛屾瘡娆￠噸璇曚箣闂撮棿闅旂殑绉掓暟

Logs:
  GinLogName: "/storage/logs/gin.log"                      # 璁剧疆 gin 妗嗘灦鐨勬帴鍙ｈ闂棩蹇楋紝v1.5.xx 浠ュ悗鐨勭増鏈笉鍐嶇敓鎴恎in鍘熺敓鐨勬帴鍙ｈ闂棩蹇?
  GoSkeletonLogName: "/storage/logs/douyin-backend.log"    # 璁剧疆douyin-backend椤圭洰楠ㄦ灦杩愯鏃舵棩蹇楁枃浠跺悕锛屾敞鎰忚鍚嶇О涓嶈涓庝笂涓€鏉￠噸澶?,閬垮厤鍜?gin 妗嗘灦鐨勬棩蹇楁幒鏉備竴璧凤紝閫犳垚娣蜂贡銆?
  TextFormat: "json"                                       # 璁板綍鏃ュ織鐨勬牸寮忥紝鍙傛暟閫夐」锛歝onsole銆乯son 锛?console 琛ㄧず涓€鑸殑鏂囨湰鏍煎紡
  TimePrecision: "millisecond"                             # 璁板綍鏃ュ織鏃讹紝鐩稿叧鐨勬椂闂寸簿搴︼紝璇ュ弬鏁伴€夐」锛歴econd  銆?millisecond 锛?鍒嗗埆琛ㄧず 绉?鍜?姣 ,榛樿涓烘绉掔骇鍒?
  MaxSize: 10                                              # 姣忎釜鏃ュ織鐨勬渶澶у昂瀵?浠B涓哄崟浣嶏級锛?瓒呰繃璇ュ€硷紝绯荤粺灏嗕細鑷姩杩涜鍒囧壊
  MaxBackups: 7                                            # 淇濈暀鏃ф棩蹇楁渶澶т釜鏁?
  MaxAge: 15                                               # 淇濈暀鏃ф棩蹇楁渶澶уぉ鏁?
  Compress: false                                          # 鏃ュ織澶囦唤鏃讹紝鏄惁杩涜鍘嬬缉

Websocket:                        # 璇ユ湇鍔′笌Http鍏锋湁鐩稿悓鐨刬p銆佺鍙ｏ紝鍥犳涓嶉渶瑕侀澶栬缃鍙?
  Start: 1                        # 榛樿涓嶅惎鍔ㄨ鏈嶅姟锛?=鍚姩锛?=涓嶅惎鍔級
  WriteReadBufferSize: 20480      # 璇诲啓缂撳啿鍖哄垎閰嶅瓧鑺傦紝澶ф鑳藉瓨鍌?6800 澶氫竴鐐圭殑鏂囧瓧
  MaxMessageSize: 65535           # 浠庢秷鎭閬撹鍙栨秷鎭殑鏈€澶у瓧鑺?
  PingPeriod: 30                  # 蹇冭烦鍖呴鐜囷紝鍗曚綅锛氱
  HeartbeatFailMaxTimes: 4        # 鍏佽蹇冭烦澶辫触鐨勬渶澶ф鏁帮紙榛樿璁剧疆涓篜ingPeriod=30绉掓娴嬩竴娆★紝杩炵画4娆℃病鏈夊績璺冲氨浼氭竻闄ゅ悗绔湪绾夸俊鎭級
  ReadDeadline: 0                 # 瀹㈡埛绔湪绾挎儏鍐典笅锛屾甯哥殑涓氬姟娑堟伅闂撮殧绉掓暟蹇呴』灏忎簬璇ュ€硷紝鍚﹀垯鏈嶅姟鍣ㄥ皢浼氫富鍔ㄦ柇寮€,鍗曚綅锛氱銆?0 琛ㄧず涓嶈闄愬埗锛屽嵆鏈嶅姟鍣ㄤ笉涓诲姩鏂紑涓嶅彂閫佷换浣曟秷鎭殑鍦ㄧ嚎瀹㈡埛绔?
  WriteDeadline: 35               # 娑堟伅鍗曟鍐欏叆瓒呮椂鏃堕棿锛屽崟浣嶏細绉?

SnowFlake:
  SnowFlakeMachineId: 2               # 濡傛灉鏈」鐩悓鏃堕儴缃插湪澶氬彴鏈哄櫒锛屽苟涓旈渶瑕佸悓鏃朵娇鐢ㄨ绠楁硶锛岃涓烘瘡涓€鍙版満鍣ㄨ缃笉鍚岀殑ID锛屽尯闂磋寖鍥? [0,1023]

FileUploadSetting:
  Size: 50                            # 璁剧疆涓婁紶鏂囦欢鐨勬渶澶у€硷紝鍗曚綅锛歁锛屾敞鎰忥細 濡傛灉go鍓嶇疆nginx鏈嶅姟鍣紝nginx 榛樿闄愬埗鏂囦欢涓婁紶澶у皬涓?50 M ,鐢ㄦ埛涓婁紶鏂囦欢闄愬埗杩橀渶瑕佺户缁慨鏀?nginx 閰嶇疆
  UploadFileField: "file"             # post涓婁紶鏂囦欢鏃讹紝琛ㄥ崟鐨勯敭鍚?
  StorageDriver: "cos"              # local=鏈湴瀛樺偍锛宑os=鑵捐浜慍OS
  SourceUrlPrefix: "/public"  # 璧勬簮璁块棶URL鍓嶇紑
  UploadRootPath: "./public"  # 鏈嶅姟鍣ㄥ瓨鍌ㄨ祫婧愮殑鏍圭洰褰?
  AvatarSmallUploadFileSavePath: "/images/avatar_small/"
  AvatarLargeUploadFileSavePath: "/images/avatar_large/"
  CoverUploadFileSavePath: "/images/cover/"
  WhiteCoverUploadFileSavePath: "/images/white_cover/"
  VideoUploadFileSavePath: "/videos/source/"
  VideoCoverUploadFileSavePath: "/videos/cover/"
  Cos:
    BucketURL: "https://example-bucket.cos.ap-region.myqcloud.com"                     # 渚嬪 https://<Bucket-APPID>.cos.ap-shanghai.myqcloud.com
    BaseURL: ""                       # 瀵瑰璁块棶鍩熷悕锛屽彲濉獵OS榛樿鍩熷悕鎴栬嚜瀹氫箟CDN鍩熷悕
    SecretID: "YOUR_COS_SECRET_ID"
    SecretKey: "YOUR_COS_SECRET_KEY"
    PathPrefix: "douyin"

  AllowMimeType: #鍏佽鐨勬枃浠秏ime绫诲瀷鍒楄〃
    - "image/jpeg"                    #jpg銆乯peg鍥剧墖鏍煎紡
    - "image/png"                     #png鍥剧墖鏍煎紡
    - "image/x-icon"                  #ico鍥剧墖
    - "image/bmp"                     #bmp鍥剧墖
    - "application/zip"               #xlsx銆乨ocx銆亃ip
    - "application/x-gzip"            #tar.gz
    - "text/plain; charset=utf-8"     #txt log json绛夋枃鏈枃浠?
    - "video/mp4"      #瑙嗛鏂囦欢锛屼緥濡傦細mp4
    - "audio/mpeg"     #闊抽鏂囦欢锛屼緥濡? mp3
RabbitMq:
  HelloWorld:
    #娑堟伅鏈嶅姟鍣ㄥ湴鍧€銆佽处鍙枫€佸瘑鐮侊紝 / (鏂滄潬)琛ㄧず榛樿鐨勮櫄鎷熶富鏈猴紝濡傛灉鏄紑鍙戣€呰嚜宸卞垱寤虹殑锛岀洿鎺ヨ拷鍔犲湪 / (鏂滄潬)鍚庨潰鍗冲彲锛屼緥濡傦細amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/ginskeleton
    Addr: "amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/"
    QueueName: "helloword_queue"
    Durable: false                                        #娑堟伅鏄惁鎸佷箙鍖?
    ConsumerChanNumber: 2                                 #娑堣垂鑰呴€氶亾鏁伴噺锛堝厑璁镐竴涓秷璐硅€呬娇鐢ㄥ嚑涓繛鎺ラ€氶亾娑堣垂銆佸鐞嗘秷鎭級
    OffLineReconnectIntervalSec: 5                        #娑堣垂鑰呮帀绾垮悗,閲嶈繛闂撮殧鐨勭鏁?
    RetryCount: 5                                         #娑堣垂鑰呮帀绾垮悗,灏濊瘯閲嶈繛鏈€澶ф鏁?
  WorkQueue:
    Addr: "amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/"  #鍙傜収鍓嶆枃鍦板潃璇存槑
    QueueName: "work_queue"
    Durable: false                                        #娑堟伅鏄惁鎸佷箙鍖?
    ConsumerChanNumber: 2                                 #娑堣垂鑰呴€氶亾鏁伴噺锛堝厑璁镐竴涓秷璐硅€呬娇鐢ㄥ嚑涓繛鎺ラ€氶亾娑堣垂銆佸鐞嗘秷鎭級
    OffLineReconnectIntervalSec: 5                        #娑堣垂鑰呮帀绾垮悗,閲嶈繛闂撮殧鐨勭鏁?
    RetryCount: 5                                         #娑堣垂鑰呮帀绾垮悗,灏濊瘯閲嶈繛鏈€澶ф鏁?
  PublishSubscribe:
    Addr: "amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/"   #娑堟伅鏈嶅姟鍣ㄥ湴鍧€銆佽处鍙枫€佸瘑鐮?
    ExchangeType: "fanout"
    ExchangeName: "fanout_exchange"                       #鍗虫椂娑堟伅闃熷垪鍚嶇О锛?
    DelayedExchangeName: "delayed_fanout_exchange"        #寤惰繜娑堟伅闃熷垪鍚嶇О锛屽繀椤讳簨鍏堝湪rabbitmq 鏈嶅姟鍣ㄧ鐞嗙鎵嬪姩鍒涘缓
    Durable: false                                        #娑堟伅鏄惁鎸佷箙鍖栵紝濡傛灉鍒濆鍖栫殑鏄欢杩熸秷鎭槦鍒?閭ｄ箞璇ュ弬鏁颁細琚▼搴忓己鍒惰缃负 true
    QueueName: ""                                         #闃熷垪鍚嶇О锛屼负绌?琛ㄧず鎵€鏈夎闃呯殑娑堣垂鑰咃紙consumer锛夐兘鍙互鎺ュ彈鍒板悓鏍风殑娑堟伅锛屽鏋滆缃悕绉帮紝浼氬鑷村彧鏈夋渶鍚庝竴涓惎鍔ㄧ殑娑堣垂鑰呰兘鎺ュ彈鍒版秷鎭€?
    ConsumerChanNumber: 1                                 #娑堣垂鑰呴€氶亾鏁伴噺锛堝彂甯冦€佽闃呮ā寮忔秷璐硅€呬娇鐢ㄤ竴涓€氶亾锛岄伩鍏嶅涓€氶亾閲嶅鏀跺埌鏁版嵁锛?
    OffLineReconnectIntervalSec: 10                       #娑堣垂鑰呮帀绾垮悗,閲嶈繛闂撮殧鐨勭鏁?
    RetryCount: 5                                         #娑堣垂鑰呮帀绾垮悗,灏濊瘯閲嶈繛鏈€澶ф鏁?
  Routing:
    Addr: "amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/"   #鍙傜収鍓嶆枃鍦板潃璇存槑
    ExchangeType: "direct"
    ExchangeName: "direct_exchange"
    DelayedExchangeName: "delayed_direct_exchange"        #寤惰繜娑堟伅闃熷垪鍚嶇О锛屽繀椤讳簨鍏堝湪rabbitmq 鏈嶅姟鍣ㄧ鐞嗙鎵嬪姩鍒涘缓
    Durable: false                                        #娑堟伅鏄惁鎸佷箙鍖栵紝濡傛灉鍒濆鍖栫殑鏄欢杩熸秷鎭槦鍒?閭ｄ箞璇ュ弬鏁颁細琚▼搴忓己鍒惰缃负 true
    QueueName: ""
    OffLineReconnectIntervalSec: 10                       #娑堣垂鑰呮帀绾垮悗,閲嶈繛闂撮殧鐨勭鏁?
    RetryCount: 5                                         #娑堣垂鑰呮帀绾垮悗,灏濊瘯閲嶈繛鏈€澶ф鏁?
  Topics:
    Addr: "amqp://璐﹀彿:瀵嗙爜@ip鍦板潃:5672/"   #鍙傜収鍓嶆枃鍦板潃璇存槑
    ExchangeType: "topic"
    ExchangeName: "topic_exchange"
    DelayedExchangeName: "delayed_topic_exchange"         #寤惰繜娑堟伅闃熷垪鍚嶇О锛屽繀椤讳簨鍏堝湪rabbitmq 鏈嶅姟鍣ㄧ鐞嗙鎵嬪姩鍒涘缓
    Durable: false                                        #娑堟伅鏄惁鎸佷箙鍖栵紝濡傛灉鍒濆鍖栫殑鏄欢杩熸秷鎭槦鍒?閭ｄ箞璇ュ弬鏁颁細琚▼搴忓己鍒惰缃负 true
    QueueName: ""
    OffLineReconnectIntervalSec: 10                       #娑堣垂鑰呮帀绾垮悗,閲嶈繛闂撮殧鐨勭鏁?
    RetryCount: 5                                         #娑堣垂鑰呮帀绾垮悗,灏濊瘯閲嶈繛鏈€澶ф鏁?

# 鎺ュ彛鏉冮檺鎺у埗
Casbin:
  IsInit: 1 # 鏄惁闅忛」鐩惎鍔ㄥ悓姝ュ垵濮嬪寲锛?=鏄紱0=鍚?
  AutoLoadPolicySeconds: 5 # 鎵弿鏁版嵁搴撶瓥鐣ョ殑棰戠巼(鍗曚綅锛氱)
  TablePrefix: "tb"
  TableName: "auth_casbin_rule"  # 绋嬪簭鏈€缁堝垱寤虹殑琛ㄤ负锛?tb_casbin_rule (鍗冲湪鍓嶇紑鍜屽悕绉颁箣闂磋嚜鍔ㄦ坊鍔犱簡涓嬪垝绾?_ )
  ModelConfig: |    # 绔栫嚎 | 琛ㄧず浠ヤ笅鏁存鏂囨湰淇濇寔鎹㈣鏍煎紡
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _ , _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = (g(r.sub, p.sub) || p.sub == "*" ) && keyMatch(r.obj , p.obj) && (r.act == p.act || p.act == "*")

#楠岃瘉鐮?鍖呮嫭涓棿浠?閰嶇疆淇℃伅
Captcha:
  captchaId: "captcha_id"  # 楠岃瘉鐮乮d鎻愪氦鏃剁殑閿悕
  captchaValue: "captcha_value"   #楠岃瘉鐮佸€兼彁浜ゆ椂鐨勯敭鍚?
  length: 4   # 楠岃瘉鐮佺敓鎴愭椂鐨勯暱搴?


